name: arb_demo

sdkPath: .fvm/flutter_sdk

packages:
  - app
  - packages/*

command:
  bootstrap:
    environment:
      sdk: ^3.2.3
      flutter: ^3.16.4
    dependencies:
      flutter:
        sdk: flutter
      flutter_localizations:
        sdk: flutter
      intl: ^0.18.1
